---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-adminer
spec:
  selector:
    matchLabels:
      app: db-adminer
  template:
    metadata:
      labels:
        app: db-adminer
    spec:
      containers:
      - name: db-adminer
        image: docker.io/adminer
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
