---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: docker.io/mysql:8.0.22
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: debezium
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-data
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-pvc
