apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: daytrader-mirror-maker2
spec:
  version: 2.5.0
  replicas: 1
  connectCluster: "daytrader-kafka-aws"
  clusters:
    - alias: "daytrader-kafka-gcp"
      bootstrapServers: "<external bootstrap address>:9094"
    - alias: "daytrader-kafka-aws"
      bootstrapServers: "<external bootstrap address>:9094"
    - alias: "daytrader-kafka-ibm"
      bootstrapServers: "<external bootstrap address>:9094"
  mirrors:
    - sourceCluster: "daytrader-kafka-gcp"
      targetCluster: "daytrader-kafka-aws"
      sourceConnector:
        sourceConnector:
          config:
            replication.factor: 1
            offset-syncs.topic.replication.factor: 1
            sync.topic.acls.enabled: "false"
          heartbeatConnector:
            config:
              heartbeats.topic.replication.factor: 1
          checkpointConnector:
            config:
              checkpoints.topic.replication.factor: 1
          topicsPattern: "openshift.traderdb.outboxevent"
    - sourceCluster: "daytrader-kafka-gcp"
      targetCluster: "daytrader-kafka-ibm"
      sourceConnector:
        sourceConnector:
          config:
            replication.factor: 1
            offset-syncs.topic.replication.factor: 1
            sync.topic.acls.enabled: "false"
          heartbeatConnector:
            config:
              heartbeats.topic.replication.factor: 1
          checkpointConnector:
            config:
              checkpoints.topic.replication.factor: 1
          topicsPattern: "openshift.traderdb.outboxevent"