name: Application Build and Push
env:
   CONTAINER_REPO: "quay.io"
   CONTAINER_IMAGE_REPO: "kameshsampath/openliberty.sampledaytrader8"
on:
  push:
    branches: [ sko-demo ]

jobs:
  checkoutAndBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v2
      - name: Maven Build
        id: build_app
        run: mvn -B -DskipTests clean package --file pom.xml
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: actions/upload-artifact@v2
        name: Save build target directory
        with:
          name: buildArtifacts
          path: |
            k8s
            target
  containerBuild:
    runs-on: ubuntu-latest
    needs: [checkoutAndBuild]
    steps:
       - name: Download build target directory
         uses: actions/download-artifact@v2
         with:
          name: buildArtifacts
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1.0.3
       - name: Login to Container Registry
         uses: docker/login-action@v1
         with:
           registry: ${{ env.CONTAINER_REPO }}
           username: ${{ secrets.QUAY_USER }}
           password: ${{ secrets.QUAY_PASSWORD }}
       - name: Commit Metadata
         id: commit_metadata
         run: |
            echo "##[set-output name=sha;]$(echo $(git rev-parse --short $GITHUB_SHA))"
            echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
       - name: Build and Push to GitHub Container Registry
         id: docker_build_push
         uses: docker/build-push-action@v2
         with:
           push: true
           context: .
           file: ./Dockerfile
           registry: quay.io
           tags: |
            ${{env.CONTAINER_REPO}}/${{env.CONTAINER_IMAGE_REPO}}:${{steps.commit_metadata.outputs.branch}}-${{steps.commit_metadata.outputs.sha}}
            ${{env.CONTAINER_REPO}}/${{env.CONTAINER_IMAGE_REPO}}:latest